### ISSUE TITLE
Possible style misspelling

### ISSUE THREAD

**Issue by themightyoarfish** [waleedka/hiddenlayer#5]
https://github.com/waleedka/hiddenlayer/blob/3588dbfa81fc3b0954b6fc8c9f3c187a78e78e5e/hiddenlayer/graph.py#L324

Should this be `dotted` maybe? When I `build_graph` with a PyTorch model, I get
```
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
Warning: gvrender_set_style: unsupported style doted - ignoring
```

**Comment by philferriere** [comment]
Misspelling, for sure. Thanks for bringing it to our attention, @themightyoarfish

**Comment by waleedka** [comment]
This is one of those cases where the bug is a feature :) The lines in the graphs are supposed to be solid, and that's how we display them in the home page and the demos. The misspelling of "dotted" caused the style to be ignored and the lines were drawn solid, as they should be. Fixing the misspelling caused the lines in the graphs to be dotted, which is not the desired outcome. I replaced with an explicit "solid" value to make the intent clearer.
